name: Build and push to AWS

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo
              uses: actions/checkout@v6

            - name: Setup dotnet
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: '10.0'

            - name: Build project
              run: dotnet restore; dotnet publish -o site;

            - name: create zip package
              run: cd site; zip ../site.zip *;

            - name: Deploy to AWS EB
              uses: einaregilsson/beanstalk-deploy@v22
              with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                application_name: calculatorAPI
                environment_name: CalculatorAPI-env
                version_label: ${{ github.run_id }}
                region: eu-north-1
                deployment_package: site.zip